FROM python:3.13-alpine@sha256:5c22e02915f1e7cef3e7bc0c1128c76c632ead5ead63eabfc67a9eea252e3f72

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="prometheus-pve-sd"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/prometheus-pve-sd/"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/prometheus-pve-sd/"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/prometheus-pve-sd/"

ENV PY_COLORS=1
ENV TZ=UTC

ADD dist/prometheus_pve_sd-*.whl /

RUN apk --update add --virtual .build-deps build-base libffi-dev openssl-dev && \
    apk --no-cache upgrade xz-libs sqlite-libs && \
    pip install --upgrade --no-cache-dir pip  && \
    pip install --no-cache-dir $(find / -name "prometheus_pve_sd-*.whl") && \
    rm -f prometheus_pve_sd-*.whl && \
    rm -rf /var/cache/apk/* && \
    rm -rf /root/.cache/

USER root
CMD []
ENTRYPOINT ["/usr/local/bin/prometheus-pve-sd"]
