FROM python:3.11-alpine@sha256:bd16cc548687f25bf7cbc29c3d284c290cf63899b281f0f3a52fc697b48884c7

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="prometheus-pve-sd"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/prometheus-pve-sd/"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/prometheus-pve-sd/"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/prometheus-pve-sd/"

ENV PY_COLORS=1
ENV TZ=UTC

ADD dist/prometheus_pve_sd-*.whl /

RUN apk --update add --virtual .build-deps build-base libffi-dev openssl-dev && \
    pip install --upgrade --no-cache-dir pip && \
    pip install --no-cache-dir $(find / -name "prometheus_pve_sd-*.whl") && \
    rm -f prometheus_pve_sd-*.whl && \
    rm -rf /var/cache/apk/* && \
    rm -rf /root/.cache/

USER root
CMD []
ENTRYPOINT ["/usr/local/bin/prometheus-pve-sd"]
