---
baseURL: https://prometheus-pve-sd.geekdocs.de/
title: prometheus-pve-sd
theme: hugo-geekdoc
pygmentsUseClasses: true
pygmentsCodeFences: true

# Geekdoc configuration
disablePathToLower: true
enableGitInfo: true

# Needed for mermaid/katex shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1

params:
  description: >
    prometheus-pve-sd is a simple custom service discovery for Prometheus. It is using the Proxmox VE API
    to fetch Hosts and it's meta information to generate a Prometheus compatible file based service discovery.
  images:
    - "socialmedia2.png"

  geekdocMenuBundle: true
  geekdocToC: 3

  geekdocRepo: https://github.com/thegeeklab/prometheus-pve-sd
  geekdocEditPath: edit/main/docs

  geekdocDateFormat: "Jan 2, 2006"
  geekdocSearch: true

  geekdocLegalNotice: https://thegeeklab.de/legal-notice/#contact-information
  geekdocPrivacyPolicy: https://thegeeklab.de/legal-notice/#privacy-policy
